api_platform:
    resource: .
    type: api_platform
    prefix: /api

health:
    path: /health/ready
    controller: App\Shared\Infrastructure\Http\HealthController::ready
    methods: [GET]

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
